import scrapy
from tutorial.items import TutorialItem


class nzhangSpider(scrapy.Spider):
    name = 'nzhang'

    def start_requests(self):
        start_urls = ['http://www.0ggw.com',
                      'http://114.jxhz.com',
                      'http://www.15yunmall.com',
                      'http://www.17wacai.com',
                      'http://www.1caifu.com',
                      'http://www.1cf.com',
                      'http://www.2771777.cn',
                      'http://2qq.sofanyong.cn',
                      'http://www.51whfy.com',
                      'http://www.52peizifanxi.com',
                      'http://www.52vzhan.com',
                      'http://556940.top',
                      'http://56web.93bus.com',
                      'http://www.58yygou.com',
                      'http://www.6612991.cn',
                      'http://www.6617529.cn',
                      'http://www.77110.cn',
                      'http://www.7893611.cn',
                      'http://www.880368.com',
                      'http://www.91jiuyu.com',
                      'http://www.91jrh.com',
                      'http://www.91xiaojinyu.cn',
                      'http://www.92yoohoo.com',
                      'http://www.95yin.cn',
                      'http://www.9699963.cn',
                      'http://www.99jufu.com',
                      'http://www.a-fanyong.com',
                      'http://www.afanyong.cn',
                      'http://www.anyulc.com',
                      'http://www.aqmtsm.com',
                      'http://ask.bangwoya.com',
                      'http://www.bangwoya.com',
                      'http://www.bbs.wafuli.cn',
                      'http://www.bifenggang.net',
                      'http://www.bjdlyb.com',
                      'https://www.blowan.com',
                      'http://www.bns.wangdaidongtai.com',
                      'http://cdnmain.fanlimofang.com',
                      'http://www.cjlc.cn',
                      'http://www.cnxie8.com',
                      'http://www.dachedao.cn',
                      'http://www.dntpma84.cpthx.com',
                      'http://www.dywhfyw.com',
                      'http://www.dzsplm.com',
                      'http://www.e5er.com',
                      'http://www.etaoyg.com',
                      'http://www.etoutianxia.com',
                      'http://www.fanlimofang.com',
                      'http://www.fanlipa.com',
                      'http://www.fanlisoso.cn',
                      'http://www.fanlisoso.com',
                      'http://www.fanlisousou.cn',
                      'http://www.fanlisousou.com',
                      'http://www.fanlitou.cn',
                      'http://www.fanlitou.com',
                      'http://www.fanniuke.com',
                      'http://fanxian.77110.cn',
                      'http://www.fanyong6688.com',
                      'http://www.fanyongyi.cn',
                      'http://www.fanyongyi.com',
                      'http://www.fastfanyong.cn',
                      'http://www.fastfanyong.com',
                      'https://www.ff8.cn',
                      'http://www.flw360.com',
                      'http://www.forexre.com',
                      'http://www.fuanchang.com',
                      'http://www.fx2088.com',
                      'http://www.fxdzx.com',
                      'http://www.fyhhlm.com',
                      'http://www.fylm123.com',
                      'http://www.fyzjhome.com',
                      'http://www.gei.1cf.com',
                      'http://www.gjfanyongwang.com',
                      'http://www.gyfanyong.com',
                      'http://www.h5.04.1cf.com',
                      'http://www.haikuzuan.com',
                      'http://www.hanamc.com.cn',
                      'http://www.haoyangmao.me',
                      'http://www.hengxfl.com',
                      'http://www.hongzunkj.cn/',
                      'http://www.huijinke.com',
                      'http://www.hujin110.com',
                      'http://www.hujinfai.com',
                      'http://www.hujinfanli.com',
                      'https://huochetou123.com',
                      'http://www.hym777.com',
                      'http://www.hzzrlp.com',
                      'http://insure.weibiao123.com',
                      'http://www.jdzi.net.cn',
                      'http://www.je2o.com',
                      'http://www.jiaoyiwangchao.com',
                      'http://www.jikefl.com',
                      'http://www.jikejk.com',
                      'https://jikelc.com',
                      'http://www.jingwentuanjian.com',
                      'http://www.jinpaifanyong.com',
                      'https://www.jinpaiwaihui.com',
                      'http://www.jubaosuo.cn',
                      'http://www.jxhz.com',
                      'http://www.jyfanyong.com',
                      'http://www.kgfyw.com',
                      'http://www.kuaijiaxi.com',
                      'http://www.labaca.cn',
                      'http://www.ldiandian.com',
                      'http://www.lecaizhu.com',
                      'http://www.ledouwan.com',
                      'http://www.lehuo02.com',
                      'http://licai.bangwoya.com',
                      'http://www.licaishop.com',
                      'http://m.byfyw.com',
                      'http://m.fanlitou.com',
                      'http://m.kuaijiaxi.com',
                      'http://m.yinjifen.com',
                      'http://www.masduo.com',
                      'http://www.mayiwacai.com',
                      'http://www.micaiw.cn',
                      'http://www.morefanli.com',
                      'http://www.msdfanli.com',
                      'http://www.niuniufanyong.com',
                      'https://www.njbdgd.com',
                      'http://www.nyb168.com',
                      'http://www.p2plm.com',
                      'http://www.poyunwen.com',
                      'http://www.qfanyong.com',
                      'http://qhfy88.com',
                      'http://www.qianyouke.com',
                      'http://www.qihaoip.com',
                      'http://www.qingshancaifu.com',
                      'http://www.qqq.1cf.com',
                      'https://www.quanminjizhang.cn',
                      'http://www.qunalc.com',
                      'http://www.qusoucai.com',
                      'http://www.qutou8.cn',
                      'http://www.ririfanyong.com',
                      'http://www.rongpuhui.com',
                      'http://www.rrf888.com',
                      'http://www.rrfyw888.com',
                      'http://www.sdsstd.com',
                      'http://www.shitouke.cn',
                      'http://www.shunfanyong.com',
                      'http://www.shuoshiyu.com',
                      'http://shuoshiyu.yintiao.net',
                      'http://www.soucaimall.com',
                      'http://www.souzhuangw.cn',
                      'http://www.sq360.top',
                      'http://www.sxxgzm.com',
                      'http://www.syc18.com',
                      'http://www.taitongjinrong.cn',
                      'http://www.taitongjinrong.com',
                      'http://www.taoqianba.cn',
                      'http://tfy.tianjf.com',
                      'http://www.tfylicai.com',
                      'http://www.thfanyong.com',
                      'http://www.tianjue360.cn',
                      'http://www.tiantfyw.com',
                      'http://www.tiantianfany.com',
                      'http://www.tiantianfanyong.com',
                      'http://www.tiantianfyw.com',
                      'http://www.tiaoyong.com',
                      'http://www.tjf.1cf.com',
                      'http://www.tlifan.com',
                      'http://www.toufan.cn',
                      'http://www.ttycai.com',
                      'http://www.tuancai88.com',
                      'http://www.tuhaofanyong8888.com',
                      'http://www.txfanyongwang.com',
                      'http://www.tyfanyong.com',
                      'http://vip.cf66.cc',
                      'http://www.wafuli.cn',
                      'http://www.waihui6.cn',
                      'http://www.waihuishijia.com',
                      'http://www.wangdaileida.com',
                      'http://www.wangdaipinpai.cn',
                      'http://www.wangdaitm.com',
                      'http://www.weicai10.com',
                      'http://www.wkfanyongwang.com',
                      'http://www.woaixianhuo.cn',
                      'http://www.wodeweixiaozhan.com',
                      'http://www.wujieshenghuo.com',
                      'http://www.wuyoufanli.com',
                      'http://www.wwcj99.com',
                      'https://www.x007.com.cn',
                      'http://www.xfqqzs.com',
                      'http://www.xhfylm.com',
                      'http://www.xiaoqingw.com',
                      'http://www.xindejinfu.cn',
                      'http://www.xindejinfu.com',
                      'http://www.xindejinfu.com.cn',
                      'http://www.xindejinfu.top',
                      'http://www.yinjifen.com',
                      'http://www.yiqiwacai.com',
                      'http://www.yjllm.com',
                      'http://www.ynhjwl.com',
                      'http://www.ynlyj.com',
                      'http://www.youyongwang99.com',
                      'http://www.yplus188.com',
                      'http://www.ytx88888.com',
                      'http://www.yunlianhui.cn',
                      'http://www.z722.com',
                      'http://www.zgshangwu.com',
                      'http://www.zhangdai360.com',
                      'https://www.zhihuibox.com',
                      'http://www.zhongyaofanli.com',
                      'http://zhqhpz888.com',
                      'http://www.zhuanfanyong.cn',
                      'http://www.zhuankezj.com',
                      'http://www.zongtou123.com',
                      'http://www.zongtoufx.com',
                      'http://www.zongtoufy.com',
                      'http://www.zongtouw.com',
                      'http://www.ztzhijia.com',
                      'http://www.ztzj123.com']
        for url in start_urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        item = TutorialItem()

        item['title'] = response.xpath('//title/text()').extract()
        item['keywords'] = response.xpath("//meta[@name='keywords']/@content")[0].extract()
        item['description'] = response.xpath("//meta[@name='description']/@content")[0].extract()
        item['url'] = response.url

        # item['body'] = response.body
        # item['unicode'] = response.body_as_unicode().strip()

        yield item
